---
title: "HW04"
author: "Elena Burkey"
date: "3/8/2021"
output:
  html_document:
    theme: Paper
  gitub_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
```

## Unemployment Rates in Florida 

```{r}
if(!dir.exists(here::here("Finale_Project", "data")))
{dir.create(here::here("Finale_Project", "data", "Unemployment_Rate.csv"))}
```

```{r}
Data_FL <- read_csv(here::here("Finale_Project", "data", "Unemployment_Rate.csv"))
```

```{r}
as_tibble(Data_FL)
```

```{r}
str(Data_FL)
```

```{r}
Summary <- Data_FL %>%
  summarize(across(c(TotalPopul : PercentP_7),
                   list( mu = ~ mean (.x, na.rm = TRUE),
                         sd = ~ sd (.x, na.rm = TRUE),
                         min = ~ min (.x, na.rm = TRUE),
                         max = ~ max (.x, na.rm = TRUE))))
```

```{r}
Plot1 <- Summary %>%
ggplot() +
  aes(y = "TotalPopul", x = "Unemployme") +
  geom_jitter(alpha = .5) +
  theme_classic() 
Plot1
```

```{r}
ggplot(Data_FL, aes(Median_Age)) +
  geom_bar() +
  theme_classic() 
```

```{r}
ggplot(Data_FL) +
  aes(y = "Geography", x = "Unemployme") +
  geom_jitter(alpha = .5) +
  theme_classic() 
``` 