---
title: "HW03"
author: "Elena Burkey"
date: "2/22/2021"
output: 
  html_document:
    theme: paper
  github_document: default
---



```{R setup, include = False}
knitr::opts_chunk$set(echo = TRUE)
dictionary <- readr::read_csv("green_dictionary.csv")
green_data <- readr::read_csv("green_data.csv")
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(reshape2)
library(ggdist)
```

# 1)
Inspect the item responses (e.g., with graphs or by summarizing distinct values).     Is anything unusual?


```{R}
Q1set = filter(green_data, id == 5549)
Q1set.1 <- as.data.frame(t(as.matrix(Q1set)))
```

```{R}
green_data.melt <- melt(green_data, measures.var = across (c:green1:open10))
ggplot(green_data.melt)+
  aes(y = value, x = id)+
  geom_point(alpha = 0.5)+
  theme_classic()
```
```{R}
summary(green_data.melt)
```
- based at the data at hand there are certain issues that can be found in the data set such as the data having errors such as seen in the Value table that states that Min. = -99.000 which is not correct.  


# 2)
Compute total scores for the four scales. 
     Recode variables as needed.
     
     
```{R}

```     

# 3) 
Rescale the variables so that they go from 0-100 instead of the original range.
     Name the recaled variables `*_pomp`.
```{R}

```     

# 4)
Make plots that illustrate the distributions of the 4 POMP-scored variables.
```{R}

```
# 5)
Make scatterplots showing the relationships between **green reputation** and each personality trait.
     Include trend lines for **students** and **non-students**.
     What do these plots show?
```{R}

```

# 6)
Compare **green reputation** for students and non-students using a **rainfall plot** (bar + density + data points).
```{R}

```

# 7)
Compute a summary table of means, SDs, medians, minima, and maxima for the four total scores for students and non-students.
```{R}  

```
